# Generated by Django 4.2.3 on 2023-07-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=9, max_digits=15)),
                ('longitude', models.DecimalField(decimal_places=9, max_digits=15)),
                ('detailing_type', models.CharField(max_length=20)),
                ('data', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('latitude', 'longitude', 'detailing_type')},
            },
        ),
    ]
