# Generated by Django 4.2.3 on 2023-07-15 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weatherdata',
            unique_together=set(),
        ),
    ]
